### PR TITLE
Spring Boot 2.0.0

### PR DESCRIPTION
**Pull request by heruan**
Minimal changes to get the starter working in Spring Boot 2.0.0.

### CODE REVIEW

**Comment by apottere** [comment]
Thanks for taking the time to do this.  I thought I had commented before, but I must have forgotten.  Since 2.0.0 is only a milestone right now, I'm waiting for the first release before pulling this.

**Comment by kganger** [comment]
We are trying to get graphql migrated to spring boot 2.0. Its now in M7. I understand hesitancy to add the milestone repositories to your gradle file. Would it be possible to get this in a snapshot release at least?

**Comment by dajaro** [comment]
@apottere If there is no backwards compatible solution for Spring Boot 2, should branches for Spring Boot 1.x and 2.x compatible version be created for this repository? This would allow for maintenance/patches for the Spring Boot 1 compatible version while having a Spring Boot 2 compatible version.

**Comment by kganger** [comment]
@dajaro I think the solution in @huerans solution is backwards compatible. It’s a simple change in the autoconfigure class. 

I did apply his changes and have been testing locally with spring boot 2.0 graphql seems to be working fine

**Pull request merged**
