### PR TITLE
Websocket support

### PR DESCRIPTION
**Pull request by oliemansm**
I've merged in all latest changes and added a working example for subscriptions. Can you review so we can merge this one and release it? I haven't updated the version number of this one yet I believe.

### CODE REVIEW

**Comment by oliemansm** [comment]
graphql-java-servlet needs to be merged (and released) first before this one can successfully be released. It depends on the new graphl-java-servlet version 6.0.0.

**Comment by apottere** [comment]
@oliemansm graphql-java-servlet `6.0.0` is syncing now, it can take a while for it to show up though: https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.graphql-java%22%20AND%20a%3A%22graphql-java-servlet%22

**Comment by apottere** [comment]
@oliemansm I'm going to release 6.1.0 of graphql-java-servlet real quick to pick up https://github.com/graphql-java/graphql-java-servlet/commit/e932a55d70db4492af818277e02f1d358cca2fa3 before releasing this

**Comment by apottere** [comment]
Released in `5.0.0`!

**Comment by oliemansm** [comment]
Thanks!

**Pull request merged**
