### PR TITLE
Upgrade to latest GraphiQL

### PR DESCRIPTION
**Pull request by donbeave**
And also added an ability to set js version from `application.yml` config file, it can help to update to minor versions without waiting for the release of new `graphiql-spring-boot-starter`.

### CODE REVIEW

**Comment by donbeave** [comment]
@apottere I can add the ability to serve local files by property, which will be available with the jar file from webjars:

```
compile 'org.webjars.npm:graphiql:0.11.5'
```

What do you think about this idea?

**Comment by apottere** [comment]
I think that would work, but we've had some issues with webjars in the past (#19).  I think it would be safer to just use packaged files instead - I merged a PR earlier that had the required files included.  I would love to use webjars because it's much cleaner, but not if they're flaky.

**Comment by donbeave** [comment]
@apottere Can you explain what problem with webjars you met before?

**Comment by apottere** [comment]
The PR I linked references #14 and #18, both of which were issues caused by webjars not being resolvable intermittently (at build time).

**Comment by donbeave** [comment]
Got it. I'll add support to specify CDN version from application config or use embedded files by default.

**Comment by donbeave** [comment]
Done. @apottere, added 2 properties:
```
graphiql.cdn.enabled: true
graphiql.cdn.version: 0.11.9
```

Default values:
```
graphiql.cdn.enabled: false
graphiql.cdn.version: 0.11.11
```

**Comment by donbeave** [comment]
Sorry for disturbing you, @apottere any progress on this task?

**Comment by marceloverdijk** [comment]
This would indeed be a nice enhancement to easily use the latest graphiql version.

**Comment by oliemansm** [comment]
Thanks @donbeave, looks good to me. Could you as a final touch just add those properties to the README as well to keep that up to date? There's already a section for it in https://github.com/graphql-java/graphql-spring-boot#enable-graphiql.

**Pull request merged**
