### PR TITLE
Make Voyager Work Offline (Resolves #94)

### LINKED ISSUE #94: Make Voyager Work Offline
Hey Guys,

Voyager looks really cool, and I've wondered if it's possible to make it work offline like Graphiql.

Thanks for this awesome library :)

### PR DESCRIPTION
**Pull request by aviadavretz**

### CODE REVIEW

**Comment by oliemansm** [comment]
Great, thanks! Let's hope version 5.2.3 of graphql-tools is available central quickly now to fix the build error.

**Comment by apottere** [comment]
@oliemansm I have a ticket here, hopefully it gets fixed before the weekend: https://issues.sonatype.org/browse/OSSRH-41506

**Comment by oliemansm** [comment]
@apottere Thanks for the update!

**Comment by aviadavretz** [comment]
@oliemansm 
Looks like you've closed the PR without merging

**Comment by oliemansm** [comment]
Thanks, just merged it.

**Pull request merged**
